### ISSUE TITLE
Unable to operate plugin

### ISSUE THREAD

**Issue by TheCurle** [HLSiira/Atheos-Terminal#1]
1. Install the latest development branch of Atheos
2. Setup, install, login
3. Install Terminal through the Marketplace
4. Open Terminal through the right hand bar
5. This window opens:
![image](https://user-images.githubusercontent.com/42079760/93149178-996d9880-f6ed-11ea-9a94-f999312c6f82.png)
6. Type something into the window. This happens:
![image](https://user-images.githubusercontent.com/42079760/93149198-a4c0c400-f6ed-11ea-9239-0badce6992c9.png)

The Terminal window is now frozen. You can close it and reopen it, but upon typing anything, it freezes again.

When it freezes, the following error is written to the PHP log:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Common::sendJSON() in <FOLDER>\plugins\Terminal\terminal.php:137
Stack trace:
#0 {main}
  thrown in <FOLDER>\plugins\Terminal\terminal.php on line 137
```

**Comment by HLSiira** [comment]
Hey did the latest push to master solve this issue for you?

**Comment by TheCurle** [comment]
Yes, it did. 
Thanks!

**Comment by HLSiira** [comment]
Sorry about closing this early, I hate that it does that. Let me know if you run into more problems
