### ISSUE TITLE
Terminal don't want to open

### ISSUE THREAD

**Issue by stilic** [HLSiira/Atheos-Terminal#2]
When I click to the Terminal button (I have just installed the plugin), he don't want to open.
I have checked the webpage with the Chrome's inspector and:
![image](https://user-images.githubusercontent.com/63605602/109836345-5627c780-7c44-11eb-92c8-3ed3f67f056a.png)
How I can fix this problem?

**Comment by HLSiira** [comment]
I'm sorry your dealing with this. I'll check it out, there might need some things updated in either the Terminal or Atheos repo, I have been working on changing a lot of the source and might have missed updating one.

Could you expand the error to the full trace? 

Looking at the error, it looks like it's an issue where the Terminal isn't being properly attached to the main Atheos system on the client side for some reason, but the only thing that could cause that is an issue with loading the file, something potentially wrong with the source.manager.php in Public. 

Sorry for the delayed response, I missed the email earlier.

**Comment by stilic** [comment]
![image](https://user-images.githubusercontent.com/63605602/109918309-fcacb080-7cb6-11eb-9221-363af98b28d1.png)

**Comment by HLSiira** [comment]
The error `cannot read propery 'subscribe' of undefined` leads me to believe that you're using either an outdated Terminal installation or an outdated Atheos installation, but most likely not your fault. I just pushed and merged in a TON of changes to the Atheos repo and to the terminal repo. 

Would you mind upgrading to using both the master branches and letting me know if the error persists?

I apologize for this error if that is the case, I must have messed up a pull/push somewhere and accidently upgraded something before I was ready.

**Comment by stilic** [comment]
Yes, I really want but i have erased my installation!

**Comment by HLSiira** [comment]
What do you mean?

**Comment by stilic** [comment]
The installation of the machine on who I have installed Atheos (Raspberry Pi with YunoHost) is no longer exists.

**Comment by HLSiira** [comment]
Well that kind of sucks. Sorry you had this issue then, if you decide to try Atheos again and have the issue, let me know.

As far as I can tell, I can't recreate this issue so I'll close it if that's cool. Good luck to you!
