### ISSUE TITLE
Terminal does not process inputs in Safari, iPadOS 11

### ISSUE THREAD

**Issue by togalock** [HLSiira/Atheos-Terminal#3]
On New Line, the text field skips few lines only; no input is being processed.

![IMG_1608](https://user-images.githubusercontent.com/39847836/139781375-6bbc10b9-6d10-4e6b-9a2b-ec30e9c614b2.jpeg)

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15

Build 8c1c349, PHP 7.3 on NGINX.

**Comment by HLSiira** [comment]
Mmmm, I'm not sure how to fix this. It sounds like instead of submitting the command, Enter on the iPad is simply adding a new line? Am I understanding that fully?

**Comment by togalock** [comment]
It seems like an installation issue - problem was fixed when the plugin is reinstalled. Thanks!
